### ISSUE TITLE
Clean up pathway literature references for Entrez, UniProt, WP etc

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pathway-curation-tasks#34]
Some pathways cite URLs to Entrez, UniProt etc in the Bibliography, which is problematic because the links dont work on the new site, and maybe it doesn't make sense to have links to genes/proteins in the bibliography anyway. We should look at each of these pathways and fix them.

See https://github.com/wikipathways/wikipathways.github.io/pull/108

**Comment by larsgw** [comment]
|Source|Pathways|Status|
|---|---|---|
|Entrez Gene|WP4549 × 8|Removed refs|
|Uniprot-TrEMBL|WP4549 × 4|Removed refs|
|WikiPathways|WP5313|Removed ref, since relevant datanode was already annotated with WPID|
|WikiPathways|WP5044|Keep WP refs|
|WikiPathways|WP3995|fixed|
|NA|WP4752, WP4753, WP438|added bp and db to gpml|
|NA|WP5049, WP5043|Fixed, **except one reference without a URL that is excluded on new site**|
|NA|WP1288|Fixed|
|NA|WP5044| Moved kynurenine library reference to description; keep WP ref|

**Comment by larsgw** [comment]
> which is problematic because the links dont work on the new site

The links do work now, by the way, but they might not make sense.

**Comment by khanspers** [comment]
WP4549 (Entrez Gene / Uniprot-TrEMBL) -> contacted author as a courtesy, will wait for response before making updates.
WP5049/WP5043 -> lit ref without PMID/DOI (Veldman) doesn't show up in bibliography, so added it to description. Another reference on WP5043, Almeide et al, seems properly formatted but doesn't show up on new site. @larsgw Can you check what might be wrong with it? There's another example of this in WP1288 below.
WP4752/WP4753/WP438 -> I think the references to REPAIRtoire (which aren't showing on the new site) are legitimate (I added them.....). The pathways were modeled based on KEGG (referenced) and REPAIRtoire, so they should both be listed as references IMO. 
WP1288 -> KEGG reference is missing from new site, and another reference, Pereira et al, is also not shown. 
WP3995/WP5044/WP5313 (WikiPathways) -> after thinking about this some more, maybe we should not remove these. If the author used another WP model as a reference, I don't see why we shouldn't allow them to include it in the bibliography if we are allowing links to other pathway databases like KEGG. What do you think ?@mkutmon @AlexanderPico

**Comment by larsgw** [comment]
> Another reference on WP5043, Almeide et al, seems properly formatted but doesn't show up on new site. @larsgw Can you check what might be wrong with it? There's another example of this in WP1288 below.

Almeide et al. shows up for me now.

> WP1288 -> KEGG reference is missing from new site, and another reference, Pereira et al, is also not shown

The KEGG reference needs a `bp:DB` and a `bp:ID`. As for Pereira et al., it seems like [meta-data-action](https://github.com/wikipathways/meta-data-action) did not extract that reference because it isn't referenced anywhere ([WP1288-refs.tsv](https://github.com/wikipathways/wikipathways-database/blob/76dcde728f516a45b8471a947ba7c1d247b43b1c/pathways/WP1288/WP1288-refs.tsv)).

**Comment by khanspers** [comment]
All pathways have been updated, see table.

One remaining issue: A reference that doesn't include a URL, and is missing `bp:DB` and a `bp:ID`, isn't listed on the new site. Could still be a valid reference. Going forward, these could get identified by automatic tests and the author could be instructed to add such references to the description instead.
